<nav id="menu">
	<div class="m_botones" id="mcuenta" onmouseover="efecto_menu('mcuenta','#999999');" onmouseout="efecto_menu('mcuenta','');">cuenta</div>
	<div class="m_botones" id="minicio" onmouseover="efecto_menu('minicio','#999999');" onmouseout="efecto_menu('minicio','');">Inicio</div>
	<div class="m_botones" id="mperfil" onmouseover="efecto_menu('mperfil','#999999');" onmouseout="efecto_menu('mperfil','');">Perfil</div>
	<div class="m_buscar">Buscar</div>
	<div class="m_botones" id="mzona" onmouseover="efecto_menu('mzona','#999999');" onmouseout="efecto_menu('mzona','');">Zona</div>
</nav>